### ISSUE TITLE
error: index-pack died of signal 9

### ISSUE THREAD

**Issue by timholmes** [jenkinsci/docker-jnlp-slave#144] opened 2020-01-22 14:49 UTC
When doing a simple checkout of a large repository, the POD dies of a signal 9 for an unknown reason.

**Stripped down Jenkinsfile:**
`#!groovy
podTemplate() {
  node(POD_LABEL) {
    stage('checkout') {
        checkout scm
    }
  }
}`

_The Git repo is an internal repository_

**Stack Trace**
`error: index-pack died of signal 9
fatal: index-pack failed
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2372)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1985)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:80)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:563)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:787)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:161)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:154)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:97)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 10.0.13.126/10.0.13.126:33818
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:955)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
		at sun.reflect.GeneratedMethodAccessor1667.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
		at com.sun.proxy.$Proxy120.execute(Unknown Source)
		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1105)
		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1145)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:124)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:93)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:80)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		... 1 more`

**Comment by MarkEWaite** [comment] 2020-01-22 15:03
I'm not confident which of these might be the cause, but here are some possible ideas:

1. The kubernetes component that controls the pod has decided that the git command has not responded for too long.  It issued a SIGKILL to the git process
2. Command line git ran out of memory and was killed (possibly review [stackoverflow article](https://stackoverflow.com/questions/58749290/process-inside-pod-is-oomkilled-even-though-pod-limits-not-reached))
3. Jenkins killed command line git due to timeout (usually this would be noted as a timeout rather than a `kill -9`, but maybe it was killed due to timeout)
4. Invalid credentials were provided, the command line git process hung while trying to prompt for credentials, then kubernetes saw it was idle for too long and killed it.  Command line git is configured from the git plugin to report progress during fetch.  If the log contained no progress indicators, then it may be that the provided credentials did not work
5. Command line git version in the pod is too old to be supported by Jenkins.  For example, the CLI git version supplied with CentOS 6 (1.7.1) is not supported by the git plugin

**Comment by timholmes** [comment] 2020-01-23 17:23
I found the issue.  It was in fact a OOM error.  Although I had the container memory set high on the Jenkins UI it was not carrying over to the container.  Luckily our logs were going to Splunk otherwise it would have been hard due to the POD crashing.  I found this in the Kube logs:
`'"name'":'"JENKINS_AGENT_WORKDIR'",'"value'": '"/home/jenkins/agent'"},{'"name'":'"JENKINS_URL'",
      '"value'":'"http: //rp-jenkins: 8080/'"}],'"resources'": {
        '"limits'":{'"cpu'":'"1'",
        '"memory'":'"256Mi'"},'"requests'": {
          '"cpu'":'"500m'",'"memory'": '"128Mi'"}},'"volumeMounts'":[{'"name'": '"workspace-volume'",'"mountPath'":'"/home/jenkins/agent'"
        },`

Although the JNLP container was set to this in the UI:
![image](https://user-images.githubusercontent.com/3143025/73007621-d55c9200-3dda-11ea-8198-424c6cd62b44.png)

I was able to resolve by overriding in the `containerTemplate` like this:
`containerTemplate(name: 'jnlp', image: 'jenkins/jnlp-slave:3.35-5-alpine', args: '${computer.jnlpmac} ${computer.name}',
		resourceRequestCpu: '2',
		resourceLimitCpu: '4',
		resourceRequestMemory: '2Gi',
		resourceLimitMemory: '4Gi')`

I think this is a bug because in a scripted pipeline (not declarative) it is not honoring the UI settings for the default JNLP container.  Would that be a jenkinsci/kubernetes-plugin bug?

**Comment by MarkEWaite** [comment] 2020-01-23 21:07
I don't know which project would be best to receive that bug report.  Submit to the one you think is best suited. If that is not the right project, then it will likely be assigned to a different project.

**Comment by MarkEWaite** [comment] 2020-01-23 21:08
I'd like to close this issue, since the issue is not something that is likely to be fixed by a code change in this repository.

**Comment by timholmes** [comment] 2020-01-24 02:15
Sure

**Closed** 2020-01-25 15:03 UTC

**Comment by vpolice3** [comment] 2020-09-27 11:07
i also got this issue do hv any idea hw to resolve it

**Comment by MarkEWaite** [comment] 2020-09-27 12:25
> i also got this issue do hv any idea hw to resolve it

Yes.  See the preceding comments for ideas that may resolve it.  Out of memory means that more memory needs to be allocated to the container that performs the `git fetch`.
